/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Comida;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alber
 */
public class ListarComidaView extends javax.swing.JPanel {

    /**
     * Creates new form ListarComidaView
     */
     private DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            switch (i1) {
                case 1:
                    if (i > 0) {
                        return Boolean.TRUE;
                    }else{
                        return Boolean.FALSE;
                    }
                default:
                    return Boolean.FALSE;
            }
        }
    };
    
    public ListarComidaView() {
        initComponents();
        initTableComida();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableComida = new javax.swing.JTable();
        JLtituloComida = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 35, 35));
        setPreferredSize(new java.awt.Dimension(1100, 670));

        JTableComida.setBackground(new java.awt.Color(51, 51, 51));
        JTableComida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JTableComida.setForeground(new java.awt.Color(255, 255, 255));
        JTableComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTableComida);

        JLtituloComida.setFont(new java.awt.Font("Dialog", 1, 39)); // NOI18N
        JLtituloComida.setForeground(new java.awt.Color(255, 255, 255));
        JLtituloComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLtituloComida.setText("Lista de Comidas");
        JLtituloComida.setMaximumSize(new java.awt.Dimension(352, 50));
        JLtituloComida.setMinimumSize(new java.awt.Dimension(352, 50));
        JLtituloComida.setPreferredSize(new java.awt.Dimension(352, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 165, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLtituloComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(JLtituloComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLtituloComida;
    private javax.swing.JTable JTableComida;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initTableComida() {
            this.model.addColumn("Codigo");
            this.model.addColumn("Nombre");
            this.model.addColumn("Calorias");
            this.model.addColumn("Estado");

            this.JTableComida.setModel(model);
        }



}
