/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Dietas;

import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import utils.Horario;

/**
 *
 * @author Lenovo
 */
public class Formulario2DietaComida extends javax.swing.JPanel {

    /**
     * Creates new form Formulario2DietaComida
     */
    public Formulario2DietaComida() {
        initComponents();
        setCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTDietaComida = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDietaComida = new javax.swing.JTable();
        jBCrearDietaComida = new javax.swing.JButton();
        jBEliminarDietaComida = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBoxDietaComida = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1100, 670));

        jLTDietaComida.setBackground(new java.awt.Color(51, 51, 51));
        jLTDietaComida.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLTDietaComida.setForeground(new java.awt.Color(255, 255, 255));
        jLTDietaComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTDietaComida.setText("Formulario dieta-comida");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jTableDietaComida.setBackground(new java.awt.Color(51, 51, 51));
        jTableDietaComida.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTableDietaComida.setForeground(new java.awt.Color(255, 255, 255));
        jTableDietaComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12", "ALGO", "123", null},
                {"123", "COSA", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Comida", "Porción", "Horario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDietaComida.setRowHeight(40);
        jScrollPane1.setViewportView(jTableDietaComida);
        if (jTableDietaComida.getColumnModel().getColumnCount() > 0) {
            jTableDietaComida.getColumnModel().getColumn(0).setResizable(false);
            jTableDietaComida.getColumnModel().getColumn(1).setResizable(false);
            jTableDietaComida.getColumnModel().getColumn(2).setResizable(false);
            jTableDietaComida.getColumnModel().getColumn(3).setResizable(false);
        }

        jBCrearDietaComida.setBackground(new java.awt.Color(48, 255, 167));
        jBCrearDietaComida.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBCrearDietaComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar-el-archivo.png"))); // NOI18N
        jBCrearDietaComida.setText("Guardar");
        jBCrearDietaComida.setBorder(null);
        jBCrearDietaComida.setBorderPainted(false);
        jBCrearDietaComida.setContentAreaFilled(false);
        jBCrearDietaComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCrearDietaComida.setDisabledIcon(null);
        jBCrearDietaComida.setOpaque(true);
        jBCrearDietaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearDietaComidaActionPerformed(evt);
            }
        });

        jBEliminarDietaComida.setBackground(new java.awt.Color(247, 87, 87));
        jBEliminarDietaComida.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBEliminarDietaComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jBEliminarDietaComida.setText("Eliminar");
        jBEliminarDietaComida.setBorder(null);
        jBEliminarDietaComida.setBorderPainted(false);
        jBEliminarDietaComida.setContentAreaFilled(false);
        jBEliminarDietaComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminarDietaComida.setDisabledIcon(null);
        jBEliminarDietaComida.setEnabled(false);
        jBEliminarDietaComida.setOpaque(true);
        jBEliminarDietaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarDietaComidaActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar comidas" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCrearDietaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(jBEliminarDietaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearDietaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminarDietaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxDietaComida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxDietaComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar la dieta" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTDietaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDietaComida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLTDietaComida)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxDietaComida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBEliminarDietaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarDietaComidaActionPerformed

    }//GEN-LAST:event_jBEliminarDietaComidaActionPerformed

    private void jBCrearDietaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearDietaComidaActionPerformed

    }//GEN-LAST:event_jBCrearDietaComidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearDietaComida;
    private javax.swing.JButton jBEliminarDietaComida;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxDietaComida;
    private javax.swing.JLabel jLTDietaComida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDietaComida;
    // End of variables declaration//GEN-END:variables

    private void setCombo() {
        TableColumn column = this.jTableDietaComida.getColumnModel().getColumn(3);
        JComboBox<Object> comboBox = new JComboBox();
        comboBox.addItem("Seleccione un Horario");
        comboBox.addItem(Horario.DESAYUNO);
        comboBox.addItem(Horario.ALMUERZO);
        comboBox.addItem(Horario.MERIENDA);
        comboBox.addItem(Horario.CENA);
        comboBox.addItem(Horario.SNACK);
   
        column.setCellEditor(new DefaultCellEditor(comboBox));
        column.setCellRenderer(new DefaultTableCellRenderer());
    }
}
