/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Dietas;

import AccesoADatos.DietaData;
import Entidades.Dieta;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utils.CargarComponente;
import utils.Estado;

/**
 *
 * @author Lenovo
 */
public class ListadoDietas extends javax.swing.JPanel {

    private final DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return Boolean.FALSE;
        }
    };

    private Dieta miDieta;

    public ListadoDietas() {
        initComponents();
        initTable();
        armarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDietas = new javax.swing.JTable();
        jComboBoxDietasTabla = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLTituloD = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDietas.setBackground(new java.awt.Color(51, 51, 51));
        jTableDietas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableDietas.setForeground(new java.awt.Color(255, 255, 255));
        jTableDietas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Paciente", "Fecha Inicio", "Fecha Final", "Peso Inicial", "Peso Buscado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDietas.setRowHeight(40);
        jTableDietas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableDietas);
        if (jTableDietas.getColumnModel().getColumnCount() > 0) {
            jTableDietas.getColumnModel().getColumn(0).setMinWidth(90);
            jTableDietas.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableDietas.getColumnModel().getColumn(3).setMinWidth(90);
            jTableDietas.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableDietas.getColumnModel().getColumn(4).setMinWidth(90);
            jTableDietas.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableDietas.getColumnModel().getColumn(5).setMinWidth(90);
            jTableDietas.getColumnModel().getColumn(5).setMaxWidth(100);
            jTableDietas.getColumnModel().getColumn(6).setMinWidth(90);
            jTableDietas.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 750, 410));

        jComboBoxDietasTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDietasTablaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxDietasTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 210, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, 30));

        jLTituloD.setFont(new java.awt.Font("Roboto", 1, 39)); // NOI18N
        jLTituloD.setForeground(new java.awt.Color(255, 255, 255));
        jLTituloD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloD.setText("Lista de dietas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTituloD, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDietasTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDietasTablaActionPerformed
        if (this.jComboBoxDietasTabla.getSelectedItem().getClass() != String.class) {
            CargarComponente.borrarFilas(jTableDietas, model);
            Estado estado = (Estado) jComboBoxDietasTabla.getSelectedItem();
            List<Dieta> ListaDieta = DietaData.buscarDietas(estado);

            if (ListaDieta.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna dieta.");
                return;
            }

            for (Dieta dieta : ListaDieta) {
                String paciente = dieta.getPaciente().getNombre() + ", " + dieta.getPaciente().getApellido();

                this.model.addRow(new Object[]{
                    dieta.getIdDieta(),
                    dieta.getNombre(),
                    paciente,
                    dieta.getFechaInicial(),
                    dieta.getFechaFinal(),
                    dieta.getPesoInicial(),
                    dieta.getPesoInicial()
                });
            }
        }
    }//GEN-LAST:event_jComboBoxDietasTablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> jComboBoxDietasTabla;
    private javax.swing.JLabel jLTituloD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDietas;
    // End of variables declaration//GEN-END:variables

    private void armarCombo() {
        this.jComboBoxDietasTabla.removeAll();
        this.jComboBoxDietasTabla.addItem("Seleccione un Estado");
        this.jComboBoxDietasTabla.addItem(Estado.TODOS);
        this.jComboBoxDietasTabla.addItem(Estado.ACTIVO);
        this.jComboBoxDietasTabla.addItem(Estado.INACTIVOS);
        this.jComboBoxDietasTabla.setSelectedIndex(0);
    }

    private void initTable() {
        this.model.addColumn("Código");
        this.model.addColumn("Nombre");
        this.model.addColumn("Paciente");
        this.model.addColumn("Fecha Inicio");
        this.model.addColumn("Fecha Fin");
        this.model.addColumn("Peso Inicial");
        this.model.addColumn("Peso Final");
        
        this.jTableDietas.setModel(model);
        
        JTableHeader tableHeader = jTableDietas.getTableHeader();
        tableHeader.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setPreferredSize(new Dimension(c.getWidth(), 40)); 
                c.setBackground(Color.GRAY); 
                c.setForeground(Color.WHITE);
                return c;
            }
        });
        
        tableHeader.getColumnModel().getColumn(0).setPreferredWidth(30);
      
    }

}
