/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.BorderLayout;
import java.awt.Container;
import javafx.animation.Animation;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.AnimationPanel;
import utils.PanelRound;

/**
 *
 * @author Pc Chavez
 */
public class PacientesView extends javax.swing.JPanel {

    /**
     * Creates new form PacientesView
     */
    utils.AnimationPanel mover = new AnimationPanel();
    private final DeskNutricionista contenedor;
    public PacientesView(DeskNutricionista ContentPanel) {
        initComponents();
        contenedor = ContentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PRFondo = new utils.PanelRound();
        jBFormularioP = new javax.swing.JButton();
        jBListarP = new javax.swing.JButton();
        jBHistorialPaciente = new javax.swing.JButton();

        setBackground(java.awt.Color.lightGray);
        setMinimumSize(new java.awt.Dimension(1030, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(117, 10, 10));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU DEL PACIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1100, 40));
        jLabel1.getAccessibleContext().setAccessibleName("MENU ");

        PRFondo.setBackground(new java.awt.Color(219, 219, 219));
        PRFondo.setRoundBottomLeft(40);
        PRFondo.setRoundBottomRight(40);
        PRFondo.setRoundTopLeft(40);
        PRFondo.setRoundTopRight(40);
        PRFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBFormularioP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBFormularioP.setText("FORMULARIO ");
        jBFormularioP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, null, null, java.awt.Color.lightGray));
        jBFormularioP.setBorderPainted(false);
        jBFormularioP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFormularioP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBFormularioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFormularioPActionPerformed(evt);
            }
        });
        PRFondo.add(jBFormularioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 370, 90));

        jBListarP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBListarP.setText("LISTAR ");
        jBListarP.setActionCommand("LISTADO PACIENTE");
        jBListarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBListarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBListarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarPActionPerformed(evt);
            }
        });
        PRFondo.add(jBListarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 370, 90));

        jBHistorialPaciente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBHistorialPaciente.setText("HISTORIAL");
        jBHistorialPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBHistorialPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBHistorialPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistorialPacienteActionPerformed(evt);
            }
        });
        PRFondo.add(jBHistorialPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 370, 90));

        add(PRFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 560, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void jBHistorialPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistorialPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBHistorialPacienteActionPerformed

    private void jBListarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBListarPActionPerformed

    private void jBFormularioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFormularioPActionPerformed
       showComponents(new FormularioPacienteView());
    }//GEN-LAST:event_jBFormularioPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.PanelRound PRFondo;
    private javax.swing.JButton jBFormularioP;
    private javax.swing.JButton jBHistorialPaciente;
    private javax.swing.JButton jBListarP;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

  private void showComponents(JPanel panel) {   
        this.contenedor.getjPSetup().removeAll();
        this.contenedor.getjPSetup().add(panel, BorderLayout.CENTER);
        this.contenedor.getjPSetup().validate();
        this.contenedor.getjPSetup().repaint();      
    }

}
