/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Pc Chavez
 */
public class PacientesView extends javax.swing.JPanel {

    /**
     * Creates new form PacientesView
     */
    public PacientesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new utils.PanelRound();
        jBFormularioP = new javax.swing.JButton();
        jBListarP = new javax.swing.JButton();
        jBHistorialPaciente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(java.awt.Color.lightGray);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(219, 219, 219));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBFormularioP.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jBFormularioP.setText("Formulario");
        jBFormularioP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.black));
        jBFormularioP.setBorderPainted(false);
        jBFormularioP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFormularioP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBFormularioP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBFormularioPFocusGained(evt);
            }
        });
        jBFormularioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFormularioPActionPerformed(evt);
            }
        });
        panelRound1.add(jBFormularioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 240, 70));

        jBListarP.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jBListarP.setText("Listar ");
        jBListarP.setActionCommand("LISTADO PACIENTE");
        jBListarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBListarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBListarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarPActionPerformed(evt);
            }
        });
        panelRound1.add(jBListarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 240, 70));

        jBHistorialPaciente.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jBHistorialPaciente.setText("Historial");
        jBHistorialPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBHistorialPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBHistorialPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistorialPacienteActionPerformed(evt);
            }
        });
        panelRound1.add(jBHistorialPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 240, 70));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Abre el formulario para completar, modificar o eliminar los datos del paciente<html>");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 70));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>Explora el listado de tus pacientes, activos y no activos<html>");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 70));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>Consulta el historial de cada paciente, con el registro cronológico de su dieta o dietas <html>");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, 70));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 560, 400));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Linux Libertine G", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText(" Home Paciente");
        jPanel1.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo paciente.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void jBHistorialPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistorialPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBHistorialPacienteActionPerformed

    private void jBListarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBListarPActionPerformed

    private void jBFormularioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFormularioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFormularioPActionPerformed

    private void jBFormularioPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBFormularioPFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFormularioPFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFormularioP;
    private javax.swing.JButton jBHistorialPaciente;
    private javax.swing.JButton jBListarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private utils.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
