/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paciente;

import AccesoADatos.PacienteData;
import Entidades.Paciente;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import utils.Estado;
import utils.Validacion;

/**
 *
 * @author Lenovo
 */
public class FormularioPacienteView extends javax.swing.JPanel {

    private Paciente miPaciente;

    public FormularioPacienteView() {
        initComponents();
        this.jBBuscar.setToolTipText("Buscar");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGrupoSexo = new javax.swing.ButtonGroup();
        jLTitulo = new javax.swing.JLabel();
        PRSeccion = new utils.PanelRound();
        jSNombre = new javax.swing.JSeparator();
        jTFNombre = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jLDni = new javax.swing.JLabel();
        jTFDni = new javax.swing.JTextField();
        jSDni = new javax.swing.JSeparator();
        jLApellido = new javax.swing.JLabel();
        jSApellido = new javax.swing.JSeparator();
        jTFApellido = new javax.swing.JTextField();
        jSDomicilio = new javax.swing.JSeparator();
        jTFDomicilio = new javax.swing.JTextField();
        jLDomicilio = new javax.swing.JLabel();
        jLFechaNac = new javax.swing.JLabel();
        jLTelefono = new javax.swing.JLabel();
        jSTelefono = new javax.swing.JSeparator();
        jTFTelefono = new javax.swing.JTextField();
        jLPeso = new javax.swing.JLabel();
        jTFPeso = new javax.swing.JTextField();
        jSPeso = new javax.swing.JSeparator();
        jLPesoDeseado = new javax.swing.JLabel();
        jTFPesoDeseado = new javax.swing.JTextField();
        jSNombre6 = new javax.swing.JSeparator();
        jSAltura = new javax.swing.JSeparator();
        jTFAltura = new javax.swing.JTextField();
        jLcm = new javax.swing.JLabel();
        jBEditar = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jDFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLSexo = new javax.swing.JLabel();
        jLKg = new javax.swing.JLabel();
        jRMasculio = new javax.swing.JRadioButton();
        jRFemenino = new javax.swing.JRadioButton();
        jLAltura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 35, 35));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setBackground(new java.awt.Color(51, 51, 51));
        jLTitulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Formulario paciente");
        add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 790, -1));

        PRSeccion.setBackground(new java.awt.Color(51, 51, 51));
        PRSeccion.setRoundBottomLeft(50);
        PRSeccion.setRoundBottomRight(50);
        PRSeccion.setRoundTopLeft(50);
        PRSeccion.setRoundTopRight(50);
        PRSeccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSNombre.setForeground(new java.awt.Color(255, 255, 255));
        jSNombre.setToolTipText("");
        jSNombre.setOpaque(true);
        jSNombre.setPreferredSize(new java.awt.Dimension(50, 2));
        PRSeccion.add(jSNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 180, -1));

        jTFNombre.setBackground(new java.awt.Color(35, 35, 35));
        jTFNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(204, 204, 204));
        jTFNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTFNombre.setCaretColor(new java.awt.Color(51, 153, 255));
        jTFNombre.setSelectionColor(new java.awt.Color(102, 102, 102));
        jTFNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNombreFocusLost(evt);
            }
        });
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        PRSeccion.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, 40));

        jLNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLNombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre.setText("Nombre");
        PRSeccion.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jLDni.setBackground(new java.awt.Color(255, 255, 255));
        jLDni.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLDni.setForeground(new java.awt.Color(255, 255, 255));
        jLDni.setText("DNI");
        PRSeccion.add(jLDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jTFDni.setBackground(new java.awt.Color(35, 35, 35));
        jTFDni.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTFDni.setForeground(new java.awt.Color(204, 204, 204));
        jTFDni.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTFDni.setCaretColor(new java.awt.Color(51, 153, 255));
        jTFDni.setSelectionColor(new java.awt.Color(102, 102, 102));
        jTFDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFDniFocusLost(evt);
            }
        });
        jTFDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDniActionPerformed(evt);
            }
        });
        jTFDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDniKeyTyped(evt);
            }
        });
        PRSeccion.add(jTFDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 170, 40));

        jSDni.setForeground(new java.awt.Color(255, 255, 255));
        jSDni.setToolTipText("");
        jSDni.setOpaque(true);
        PRSeccion.add(jSDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 170, -1));

        jLApellido.setBackground(new java.awt.Color(255, 255, 255));
        jLApellido.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLApellido.setText("Apellido");
        PRSeccion.add(jLApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 20));

        jSApellido.setForeground(new java.awt.Color(255, 255, 255));
        jSApellido.setToolTipText("");
        jSApellido.setOpaque(true);
        jSApellido.setPreferredSize(new java.awt.Dimension(50, 2));
        PRSeccion.add(jSApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 180, -1));

        jTFApellido.setBackground(new java.awt.Color(35, 35, 35));
        jTFApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTFApellido.setForeground(new java.awt.Color(204, 204, 204));
        jTFApellido.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTFApellido.setCaretColor(new java.awt.Color(51, 153, 255));
        jTFApellido.setSelectionColor(new java.awt.Color(102, 102, 102));
        jTFApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFApellidoFocusLost(evt);
            }
        });
        jTFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFApellidoActionPerformed(evt);
            }
        });
        PRSeccion.add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 180, 40));

        jSDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        jSDomicilio.setToolTipText("");
        jSDomicilio.setOpaque(true);
        jSDomicilio.setPreferredSize(new java.awt.Dimension(50, 2));
        PRSeccion.add(jSDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 240, -1));

        jTFDomicilio.setBackground(new java.awt.Color(35, 35, 35));
        jTFDomicilio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTFDomicilio.setForeground(new java.awt.Color(204, 204, 204));
        jTFDomicilio.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTFDomicilio.setCaretColor(new java.awt.Color(51, 153, 255));
        jTFDomicilio.setSelectionColor(new java.awt.Color(102, 102, 102));
        jTFDomicilio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDomicilioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFDomicilioFocusLost(evt);
            }
        });
        jTFDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDomicilioActionPerformed(evt);
            }
        });
        PRSeccion.add(jTFDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 240, 40));

        jLDomicilio.setBackground(new java.awt.Color(255, 255, 255));
        jLDomicilio.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        jLDomicilio.setText("Domicilio");
        PRSeccion.add(jLDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLFechaNac.setBackground(new java.awt.Color(255, 255, 255));
        jLFechaNac.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLFechaNac.setForeground(new java.awt.Color(255, 255, 255));
        jLFechaNac.setText("Fecha de nacimiento");
        PRSeccion.add(jLFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jLTelefono.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLTelefono.setText("Telefono");
        PRSeccion.add(jLTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jSTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jSTelefono.setToolTipText("");
        jSTelefono.setOpaque(true);
        jSTelefono.setPreferredSize(new java.awt.Dimension(50, 2));
        PRSeccion.add(jSTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 120, -1));

        jTFTelefono.setBackground(new java.awt.Color(35, 35, 35));
        jTFTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(204, 204, 204));
        jTFTelefono.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTFTelefono.setCaretColor(new java.awt.Color(51, 153, 255));
        jTFTelefono.setSelectionColor(new java.awt.Color(102, 102, 102));
        jTFTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFTelefonoFocusLost(evt);
            }
        });
        jTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTelefonoActionPerformed(evt);
            }
        });
        PRSeccion.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 120, 40));

        jLPeso.setBackground(new java.awt.Color(255, 255, 255));
        jLPeso.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLPeso.setForeground(new java.awt.Color(255, 255, 255));
        jLPeso.setText("Peso Actual");
        PRSeccion.add(jLPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, 20));

        jTFPeso.setBackground(new java.awt.Color(35, 35, 35));
        jTFPeso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTFPeso.setForeground(new java.awt.Color(204, 204, 204));
        jTFPeso.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTFPeso.setCaretColor(new java.awt.Color(51, 153, 255));
        jTFPeso.setSelectionColor(new java.awt.Color(102, 102, 102));
        jTFPeso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFPesoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFPesoFocusLost(evt);
            }
        });
        jTFPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesoActionPerformed(evt);
            }
        });
        jTFPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPesoKeyTyped(evt);
            }
        });
        PRSeccion.add(jTFPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 90, 40));

        jSPeso.setForeground(new java.awt.Color(255, 255, 255));
        jSPeso.setToolTipText("");
        jSPeso.setOpaque(true);
        jSPeso.setPreferredSize(new java.awt.Dimension(50, 2));
        PRSeccion.add(jSPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 90, -1));

        jLPesoDeseado.setBackground(new java.awt.Color(255, 255, 255));
        jLPesoDeseado.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLPesoDeseado.setForeground(new java.awt.Color(255, 255, 255));
        jLPesoDeseado.setText("Peso Buscado");
        PRSeccion.add(jLPesoDeseado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 100, 20));

        jTFPesoDeseado.setBackground(new java.awt.Color(35, 35, 35));
        jTFPesoDeseado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTFPesoDeseado.setForeground(new java.awt.Color(204, 204, 204));
        jTFPesoDeseado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTFPesoDeseado.setCaretColor(new java.awt.Color(51, 153, 255));
        jTFPesoDeseado.setSelectionColor(new java.awt.Color(102, 102, 102));
        jTFPesoDeseado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFPesoDeseadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFPesoDeseadoFocusLost(evt);
            }
        });
        jTFPesoDeseado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesoDeseadoActionPerformed(evt);
            }
        });
        jTFPesoDeseado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFPesoDeseadoKeyTyped(evt);
            }
        });
        PRSeccion.add(jTFPesoDeseado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 90, 40));

        jSNombre6.setForeground(new java.awt.Color(255, 255, 255));
        jSNombre6.setToolTipText("");
        jSNombre6.setOpaque(true);
        jSNombre6.setPreferredSize(new java.awt.Dimension(50, 2));
        PRSeccion.add(jSNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 90, -1));

        jSAltura.setForeground(new java.awt.Color(255, 255, 255));
        jSAltura.setToolTipText("");
        jSAltura.setOpaque(true);
        jSAltura.setPreferredSize(new java.awt.Dimension(50, 2));
        PRSeccion.add(jSAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 90, -1));

        jTFAltura.setBackground(new java.awt.Color(35, 35, 35));
        jTFAltura.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTFAltura.setForeground(new java.awt.Color(204, 204, 204));
        jTFAltura.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTFAltura.setCaretColor(new java.awt.Color(51, 153, 255));
        jTFAltura.setSelectionColor(new java.awt.Color(102, 102, 102));
        jTFAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFAlturaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFAlturaFocusLost(evt);
            }
        });
        jTFAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAlturaActionPerformed(evt);
            }
        });
        jTFAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAlturaKeyTyped(evt);
            }
        });
        PRSeccion.add(jTFAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 90, 40));

        jLcm.setBackground(new java.awt.Color(255, 255, 255));
        jLcm.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLcm.setForeground(new java.awt.Color(255, 255, 255));
        jLcm.setText("(cm)");
        PRSeccion.add(jLcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, 40));

        jBEditar.setBackground(new java.awt.Color(0, 204, 255));
        jBEditar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-editar.png"))); // NOI18N
        jBEditar.setText("Editar");
        jBEditar.setBorder(null);
        jBEditar.setBorderPainted(false);
        jBEditar.setContentAreaFilled(false);
        jBEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditar.setDisabledIcon(null);
        jBEditar.setEnabled(false);
        jBEditar.setOpaque(true);
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        PRSeccion.add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 80, 40));

        jBCrear.setBackground(new java.awt.Color(48, 255, 167));
        jBCrear.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar-el-archivo.png"))); // NOI18N
        jBCrear.setText("Crear");
        jBCrear.setBorder(null);
        jBCrear.setBorderPainted(false);
        jBCrear.setContentAreaFilled(false);
        jBCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCrear.setDisabledIcon(null);
        jBCrear.setOpaque(true);
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });
        PRSeccion.add(jBCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 80, 40));

        jBEliminar.setBackground(new java.awt.Color(247, 87, 87));
        jBEliminar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jBEliminar.setText("Eliminar");
        jBEliminar.setBorder(null);
        jBEliminar.setBorderPainted(false);
        jBEliminar.setContentAreaFilled(false);
        jBEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEliminar.setDisabledIcon(null);
        jBEliminar.setEnabled(false);
        jBEliminar.setOpaque(true);
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        PRSeccion.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 90, 40));

        jBBuscar.setBackground(new java.awt.Color(51, 153, 255));
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jBBuscar.setToolTipText("");
        jBBuscar.setBorder(null);
        jBBuscar.setBorderPainted(false);
        jBBuscar.setContentAreaFilled(false);
        jBBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBuscar.setOpaque(true);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        PRSeccion.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 80, 40));

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        jBCancelar.setToolTipText("");
        jBCancelar.setBorder(null);
        jBCancelar.setBorderPainted(false);
        jBCancelar.setContentAreaFilled(false);
        jBCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCancelar.setEnabled(false);
        jBCancelar.setOpaque(true);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        PRSeccion.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 40, 40));

        jDFechaNacimiento.setBackground(new java.awt.Color(102, 102, 102));
        jDFechaNacimiento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PRSeccion.add(jDFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 160, 35));

        jLSexo.setBackground(new java.awt.Color(255, 255, 255));
        jLSexo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLSexo.setText("Sexo");
        PRSeccion.add(jLSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        jLKg.setBackground(new java.awt.Color(255, 255, 255));
        jLKg.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLKg.setForeground(new java.awt.Color(255, 255, 255));
        jLKg.setText("(Kg)");
        PRSeccion.add(jLKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, 40));

        jRMasculio.setBackground(new java.awt.Color(51, 51, 51));
        bGrupoSexo.add(jRMasculio);
        jRMasculio.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jRMasculio.setForeground(new java.awt.Color(255, 255, 255));
        jRMasculio.setText("M.");
        PRSeccion.add(jRMasculio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jRFemenino.setBackground(new java.awt.Color(51, 51, 51));
        bGrupoSexo.add(jRFemenino);
        jRFemenino.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jRFemenino.setForeground(new java.awt.Color(255, 255, 255));
        jRFemenino.setSelected(true);
        jRFemenino.setText("F.");
        PRSeccion.add(jRFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jLAltura.setBackground(new java.awt.Color(255, 255, 255));
        jLAltura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLAltura.setForeground(new java.awt.Color(255, 255, 255));
        jLAltura.setText("Altura");
        PRSeccion.add(jLAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        add(PRSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 470, 600));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        //Llamamos a buscarPaciente y guardamos el resultado en el atributo miPaciente
        this.miPaciente = buscarPaciente();
        //verificamos que miPaciente no sea nulo y cargamos sus atributos en los campos
        if (miPaciente != null) {
            cargarCampos(miPaciente);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        //llamamos al metodo editar.
        editar();
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jTFAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAlturaActionPerformed

    private void jTFAlturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFAlturaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAlturaFocusLost

    private void jTFAlturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFAlturaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAlturaFocusGained

    private void jTFPesoDeseadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesoDeseadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesoDeseadoActionPerformed

    private void jTFPesoDeseadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFPesoDeseadoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesoDeseadoFocusLost

    private void jTFPesoDeseadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFPesoDeseadoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesoDeseadoFocusGained

    private void jTFPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesoActionPerformed

    private void jTFPesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFPesoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesoFocusLost

    private void jTFPesoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFPesoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesoFocusGained

    private void jTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTelefonoActionPerformed

    private void jTFTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTelefonoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTelefonoFocusLost

    private void jTFTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTelefonoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTelefonoFocusGained

    private void jTFDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDomicilioActionPerformed

    private void jTFDomicilioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDomicilioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDomicilioFocusLost

    private void jTFDomicilioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDomicilioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDomicilioFocusGained

    private void jTFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFApellidoActionPerformed

    private void jTFApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFApellidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFApellidoFocusLost

    private void jTFApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFApellidoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFApellidoFocusGained

    private void jTFDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDniActionPerformed

    private void jTFDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDniFocusLost
        this.jTFDni.setBackground(new Color(35, 35, 35));
        this.jLDni.setForeground(Color.WHITE);
        this.jSDni.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTFDniFocusLost

    private void jTFDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDniFocusGained
        this.jTFDni.setBackground(new Color(63, 63, 63));
        this.jLDni.setForeground(new Color(82, 168, 255));
        this.jSDni.setBackground(new Color(82, 168, 255));
    }//GEN-LAST:event_jTFDniFocusGained

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        JOptionPane.showConfirmDialog(this, ui);
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jTFNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNombreFocusLost
        this.jTFNombre.setBackground(new Color(35, 35, 35));
        this.jLNombre.setForeground(Color.WHITE);
        this.jSNombre.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTFNombreFocusLost

    private void jTFNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNombreFocusGained
        this.jTFNombre.setBackground(new Color(63, 63, 63));
        this.jLNombre.setForeground(new Color(82, 168, 255));
        this.jSNombre.setBackground(new Color(82, 168, 255));
    }//GEN-LAST:event_jTFNombreFocusGained

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        //Llamamos al metodo limpiarCampos 
        limpiarCampos();
        //Llamamos invertirEstados para regresar al modo de crear un paciente
        invertirEstados();
        //igualamos a nulo el atributo miPaciente
        this.miPaciente = null;
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        Paciente paciente = this.crearPaciente(new Paciente());
        if (paciente != null) {
            PacienteData.CrearPaciente(paciente);
            limpiarCampos();
        }
    }//GEN-LAST:event_jBCrearActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed

        //enviamos un mensaje al usuario para que confirme la eliminacion.
        int respuesta = JOptionPane.showConfirmDialog(null, "¿esta seguro que desea eliminar el paciente? ");

        //Comparamos la respueta con la constante YES_OPTION
        if (respuesta == JOptionPane.YES_OPTION) {
            //Enviamos miPaciente a PacienteData para que lo elimine
            PacienteData.eliminarPaciente(this.miPaciente.getIdPaciente());
            limpiarCampos();
            invertirEstados();
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTFDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDniKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTFDniKeyTyped

    private void jTFAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAlturaKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTFAlturaKeyTyped

    private void jTFPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPesoKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && caracter != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_jTFPesoKeyTyped

    private void jTFPesoDeseadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPesoDeseadoKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && caracter != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_jTFPesoDeseadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utils.PanelRound PRSeccion;
    private javax.swing.ButtonGroup bGrupoSexo;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEliminar;
    private com.toedter.calendar.JDateChooser jDFechaNacimiento;
    private javax.swing.JLabel jLAltura;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLDni;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLFechaNac;
    private javax.swing.JLabel jLKg;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPeso;
    private javax.swing.JLabel jLPesoDeseado;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcm;
    private javax.swing.JRadioButton jRFemenino;
    private javax.swing.JRadioButton jRMasculio;
    private javax.swing.JSeparator jSAltura;
    private javax.swing.JSeparator jSApellido;
    private javax.swing.JSeparator jSDni;
    private javax.swing.JSeparator jSDomicilio;
    private javax.swing.JSeparator jSNombre;
    private javax.swing.JSeparator jSNombre6;
    private javax.swing.JSeparator jSPeso;
    private javax.swing.JSeparator jSTelefono;
    private javax.swing.JTextField jTFAltura;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFDni;
    private javax.swing.JTextField jTFDomicilio;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPeso;
    private javax.swing.JTextField jTFPesoDeseado;
    private javax.swing.JTextField jTFTelefono;
    // End of variables declaration//GEN-END:variables

    private Paciente crearPaciente(Paciente paciente) {
        try {
            int dni = Integer.parseInt(jTFDni.getText());

            if (!Validacion.isValidoNumero(dni)) {
                JOptionPane.showMessageDialog(this, "El dni no corresponde");
                return null;
            }

            String nombre = this.jTFNombre.getText().trim();
            String apellido = this.jTFApellido.getText().trim();
            String telefono = this.jTFTelefono.getText().trim();
            String domicilio = this.jTFDomicilio.getText().trim();

            if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || domicilio.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No puede haber campos de texto vacios.");
                return null;
            } else if (!Validacion.isValidoString(nombre) || !Validacion.isValidoString(apellido) || !Validacion.isValidoStringCNumero(domicilio)) {
                JOptionPane.showMessageDialog(this, "Alguno de los campos de texto contiene caracteres inválidos.");
                return null;
            } else if (!Validacion.isValidoNumero(telefono)) {
                JOptionPane.showMessageDialog(this, "El telefono solo puede contener numeros.");
                return null;
            } else if(telefono.matches("^\\d{7,12}$"));
            
            else{
                JOptionPane.showMessageDialog(this, "El telefono debe contener como maximo 12 numeros.");
                return null;
            }

            Date date = this.jDFechaNacimiento.getDate();

            if (date == null) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese la fecha de nacimiento.");
                return null;
            }

            LocalDate fechaNacimiento = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (fechaNacimiento.isAfter(LocalDate.now())) {
                JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede estar en el futuro.");
                return null;
            }

            Double altura = Double.parseDouble(this.jTFAltura.getText());
            Double peso = Double.parseDouble(this.jTFPeso.getText());
            Double pesoDeseado = Double.parseDouble(this.jTFPesoDeseado.getText());

            if (altura < 0 || peso < 0 || pesoDeseado < 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un valor positivo");
                return null;
            }

            String sexo = (this.jRFemenino.isSelected()) ? "Femenino" : "Masculino";

            return new Paciente(
                    nombre.trim(), apellido.trim(), dni, domicilio.trim(), telefono.trim(), sexo.trim(), fechaNacimiento, Boolean.TRUE, peso, pesoDeseado, altura
            );

        } catch (NumberFormatException e) {

            if (e.getMessage().contains(this.jTFDni.getText())) {

                JOptionPane.showMessageDialog(this, "Error en campo del DNI");
            } else if (e.getMessage().contains(this.jTFAltura.getText())) {

                JOptionPane.showMessageDialog(this, "Error en campo de la Altura");
            } else if (e.getMessage().contains(this.jTFPeso.getText())) {

                JOptionPane.showMessageDialog(this, "Error en campo del peso");
            } else if (e.getMessage().contains(this.jTFPesoDeseado.getText())) {

                JOptionPane.showMessageDialog(this, "Error en campo del peso deseado");
            }

        }
        return null;
    }

    private void limpiarCampos() {
        this.jTFDni.setText("");
        this.jTFNombre.setText("");
        this.jTFApellido.setText("");
        this.jDFechaNacimiento.setDate(null);
        this.jTFDomicilio.setText("");
        this.jTFTelefono.setText("");
        this.jRFemenino.setSelected(true);
        this.jTFAltura.setText("");
        this.jTFPeso.setText("");
        this.jTFPesoDeseado.setText("");
    }

    private Paciente buscarPaciente() {
        Paciente paciente;
        try {
            int dni = Integer.parseInt(jTFDni.getText());
            if (dni > 0) {
                paciente = PacienteData.buscarPacientePorDni(dni, Estado.TODOS);
                if (!paciente.isEstado()) {
                    int result = JOptionPane.showConfirmDialog(this, "El paciente se encuentra dado de baja. ¿Quiere darlo de alta?");
                    switch (result) {
                        case JOptionPane.YES_OPTION:
                            PacienteData.activar(paciente);
                            break;
                        case JOptionPane.NO_OPTION:
                            paciente = PacienteData.buscarPacientePorDni(dni, Estado.INACTIVOS);
                            break;
                        default:
                            return null;
                    }
                }
                return paciente;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Solo puede ingresar numeros");
        }
        return null;
    }

    private void invertirEstados() {
        this.jBCrear.setEnabled(!jBCrear.isEnabled());
        this.jBEditar.setEnabled(!jBEditar.isEnabled());
        this.jBEliminar.setEnabled(!jBEliminar.isEnabled());
        this.jBBuscar.setEnabled(!jBBuscar.isEnabled());
        this.jBCancelar.setEnabled(!jBCancelar.isEnabled());
    }

    private void cargarCampos(Paciente paciente) {
        //seteamos los atributos del paciente al los campos
        invertirEstados();

        this.jTFNombre.setText(paciente.getNombre());
        this.jTFApellido.setText(paciente.getApellido());
        this.jTFTelefono.setText(paciente.getTelefono());
        this.jTFDomicilio.setText(paciente.getDomicilio());
        ZoneId defaultZoneId = ZoneId.systemDefault();
        LocalDate fechaNacimiento = paciente.getFechaNac();
        this.jDFechaNacimiento.setDate(Date.from(fechaNacimiento.atStartOfDay(defaultZoneId).toInstant()));
        this.jTFAltura.setText(paciente.getAltura() + "");

        if (paciente.getSexo().equals("Femenino")) {
            jRFemenino.setSelected(Boolean.TRUE);
        } else {
            jRMasculio.setSelected(Boolean.TRUE);
        }

        this.jTFPeso.setText(paciente.getPeso() + "");
        this.jTFPesoDeseado.setText(paciente.getPesoBuscado() + "");

    }

    private void editar() {
        //seteamos los datos de los campos a nuestro atributo miPaciente
        Paciente pacienteAEditar = new Paciente();

        pacienteAEditar = crearPaciente(pacienteAEditar);

        if (pacienteAEditar != null) {
            pacienteAEditar.setIdPaciente(this.miPaciente.getIdPaciente());
            this.miPaciente = pacienteAEditar;
            PacienteData.modificarPaciente(miPaciente);
        }

    }
}
