/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Paciente;

import AccesoADatos.HistorialData;
import AccesoADatos.PacienteData;
import Entidades.Historial;
import Entidades.Paciente;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import utils.CargarComponente;
import utils.Estado;

/**
 *
 * @author alber
 */
public class HistorialPacientesView extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private DefaultTableModel MODEL = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }

    };

    public HistorialPacientesView() {
        initComponents();
        initTableHistorial();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTituloHistorial = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTTextoNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTHistorial = new javax.swing.JTable();
        jLNombre1 = new javax.swing.JLabel();
        jCBPaciente = new javax.swing.JComboBox<>();
        jLNombre2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(35, 35, 35));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(780, 670));
        setPreferredSize(new java.awt.Dimension(1100, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTituloHistorial.setFont(new java.awt.Font("Dialog", 1, 39)); // NOI18N
        jLTituloHistorial.setForeground(new java.awt.Color(255, 255, 255));
        jLTituloHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloHistorial.setText("Historial Pacientes");
        add(jLTituloHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 1090, 64));

        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 400, -1));

        jTTextoNombre.setBackground(new java.awt.Color(35, 35, 35));
        jTTextoNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTTextoNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTTextoNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(2, 15, 2, 15), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTTextoNombre.setCaretColor(new java.awt.Color(0, 153, 255));
        jTTextoNombre.setSelectionColor(new java.awt.Color(153, 153, 153));
        jTTextoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTTextoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTTextoNombreFocusLost(evt);
            }
        });
        jTTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTextoNombreActionPerformed(evt);
            }
        });
        jTTextoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTTextoNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTTextoNombreKeyTyped(evt);
            }
        });
        add(jTTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 400, 40));

        jTHistorial.setBackground(new java.awt.Color(51, 51, 51));
        jTHistorial.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTHistorial.setForeground(new java.awt.Color(255, 255, 255));
        jTHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTHistorial.setGridColor(new java.awt.Color(0, 0, 0));
        jTHistorial.setRowHeight(40);
        jTHistorial.setSelectionBackground(new java.awt.Color(30, 150, 117));
        jTHistorial.getTableHeader().setResizingAllowed(false);
        jTHistorial.getTableHeader().setReorderingAllowed(false);
        jTHistorial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTHistorialFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTHistorial);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 760, 454));

        jLNombre1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre1.setText("Seleccione un paciente: ");
        add(jLNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 240, 32));

        jCBPaciente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jCBPaciente.setToolTipText("");
        jCBPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPacienteActionPerformed(evt);
            }
        });
        add(jCBPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 260, 40));

        jLNombre2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLNombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLNombre2.setText("Ingrese un apellido o un nombre: ");
        add(jLNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 240, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void jTTextoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTTextoNombreFocusGained
        this.jTTextoNombre.setBackground(new Color(63, 63, 63));
    }//GEN-LAST:event_jTTextoNombreFocusGained

    private void jTTextoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTTextoNombreFocusLost
        this.jTTextoNombre.setBackground(new Color(35, 35, 35));
    }//GEN-LAST:event_jTTextoNombreFocusLost

    private void jTTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTextoNombreActionPerformed

    private void jTTextoNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTextoNombreKeyReleased
        borrarFilas();
        String texto = this.jTTextoNombre.getText();
        if (texto.isEmpty()) {
            borrarFilas();
        } else {
            List<Paciente> pacientes = PacienteData.ListarPorNombreOApellido(texto, Estado.TODOS);
            this.jCBPaciente.removeAllItems();
            this.jCBPaciente.addItem("Seleccione");
            for (Paciente p : pacientes) {
                this.jCBPaciente.addItem(p);
            }
        }

    }//GEN-LAST:event_jTTextoNombreKeyReleased

    private void jTHistorialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTHistorialFocusGained

    }//GEN-LAST:event_jTHistorialFocusGained

    private void jCBPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPacienteActionPerformed
        Object selected = this.jCBPaciente.getSelectedItem();
        if (selected != null && selected.getClass() != String.class) {
            Paciente p = (Paciente) selected;
            cargarTabla(p.getIdPaciente());
        }
    }//GEN-LAST:event_jCBPacienteActionPerformed

    private void jTTextoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTextoNombreKeyTyped
 
    }//GEN-LAST:event_jTTextoNombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> jCBPaciente;
    private javax.swing.JLabel jLNombre1;
    private javax.swing.JLabel jLNombre2;
    private javax.swing.JLabel jLTituloHistorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTHistorial;
    private javax.swing.JTextField jTTextoNombre;
    // End of variables declaration//GEN-END:variables

    private void initTableHistorial() {
        this.MODEL.addColumn("dni");
        this.MODEL.addColumn("Paciente");
        this.MODEL.addColumn("Peso");
        this.MODEL.addColumn("Fecha de Registro");

        this.jTHistorial.setModel(MODEL);
        JTableHeader tableHeader = jTHistorial.getTableHeader();
        tableHeader.setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setPreferredSize(new Dimension(c.getWidth(), 40));
                c.setBackground(Color.GRAY);
                c.setForeground(Color.WHITE);
                return this;
            }
        });
    }

    private void borrarFilas() {
        int filas = jTHistorial.getRowCount() - 1;
        for (int f = filas; f >= 0; f--) {
            MODEL.removeRow(f);
        }

    }

    private void cargarTabla(int idPaciente) {
        if (idPaciente > 0) {
            List<Historial> listHistorial = HistorialData.getHistorialPaciente(idPaciente);
            if (!listHistorial.isEmpty()) {
                CargarComponente.borrarFilas(this.jTHistorial, this.MODEL);
                for (Historial historial : listHistorial) {
                    this.MODEL.addRow(new Object[]{
                        historial.getPaciente().getDni(),
                        historial.getPaciente().getFullname(),
                        historial.getPeso(),
                        historial.getFechaRegistro()
                    });
                }
            } else {
                CargarComponente.borrarFilas(this.jTHistorial, this.MODEL);
            }
        }
    }

}
